name: ParkourTag
version: '${project.version}'
main: dev.jamieisgeek.parkourtag.ParkourTag
api-version: 1.18
authors: [ JamieIsGeek ]
description: A remix of Noxcrew's Parkour Tag Game!
commands:
  pt:
    description: Main command for Parkour Tag!
    usage: /<command> <args>
